import type { ApiModuleDescriptor } from "../../core/module/api-module.js";
import { PaymentCallbackHttpController } from "./payment-callback.facade.controller.js";
import { PaymentCallbackHttpRepository } from "./payment-callback.facade.repository.js";
import { PaymentCallbackHttpRoute } from "./payment-callback.facade.route.js";
import { PaymentCallbackHttpService } from "./payment-callback.facade.service.js";
import { PaymentCallbackHttpValidation } from "./payment-callback.facade.validation.js";
const repository=new PaymentCallbackHttpRepository();
const validation=new PaymentCallbackHttpValidation();
const service=new PaymentCallbackHttpService(repository,validation);
const controller=new PaymentCallbackHttpController(service);
const route=new PaymentCallbackHttpRoute(controller);
export const paymentCallbackModule: ApiModuleDescriptor={name:"payment-callback",mountPath:"/api/v1/payment-callbacks/sslcommerz",router:route.router};
