"use client";
import { FormEvent,useEffect,useState } from "react";
import { PageHeader } from "@/components/page-header";
import { Feedback,LoadingBlock } from "@/components/feedback";
import { apiRequest,logout } from "@/lib/api";
type S={id:string;userAgent:string|null;ipAddress:string|null;createdAt:string;lastUsedAt:string|null;current:boolean};
export default function Page(){const[sessions,setSessions]=useState<S[]>([]);const[msg,setMsg]=useState("");const[loading,setLoading]=useState(true);const load=()=>apiRequest<{data:S[]}>("/api/v1/security/sessions").then(r=>setSessions(r.data)).catch(e=>setMsg(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);
 async function change(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await apiRequest("/api/v1/security/change-password",{method:"POST",body:JSON.stringify({currentPassword:f.get("currentPassword"),newPassword:f.get("newPassword")})});e.currentTarget.reset();setMsg("Password changed. Other sessions were revoked.");load()}
 async function revoke(id:string){await apiRequest(`/api/v1/security/sessions/${id}`,{method:"DELETE"});load()}
 async function all(){if(!confirm("Log out every active session?"))return;await apiRequest("/api/v1/security/logout-all",{method:"POST"});await logout();window.location.assign("/auth/login")}
 return <><PageHeader title="Security" subtitle="Password and active session controls."><button className="btn btn-outline-danger" onClick={all}>Log out all</button></PageHeader><Feedback message={msg} variant="info"/><div className="row g-4"><div className="col-lg-5"><form className="card" onSubmit={change}><div className="card-header"><strong>Change password</strong></div><div className="card-body"><div className="mb-3"><label className="form-label">Current password</label><input className="form-control" name="currentPassword" type="password" required/></div><div><label className="form-label">New password</label><input className="form-control" name="newPassword" type="password" minLength={12} required/><div className="form-text">Other sessions will be revoked.</div></div></div><div className="card-footer bg-white"><button className="btn btn-primary">Update password</button></div></form></div><div className="col-lg-7"><div className="card"><div className="card-header"><strong>Active sessions</strong></div>{loading?<div className="card-body"><LoadingBlock/></div>:<div className="list-group list-group-flush">{sessions.map(s=><div className="list-group-item d-flex align-items-center justify-content-between gap-3" key={s.id}><div className="d-flex gap-3"><span className="file-thumb"><i className="bi bi-laptop"/></span><div><div className="fw-semibold">{s.current?"Current session":"Active session"} {s.current&&<span className="badge text-bg-success">Current</span>}</div><div className="text-secondary small">{s.userAgent??"Unknown device"}<br/>{s.ipAddress??"Unknown IP"}</div></div></div>{!s.current&&<button className="btn btn-outline-danger btn-sm" onClick={()=>revoke(s.id)}>Revoke</button>}</div>)}</div>}</div></div></div></>
}
