"use client";
import { FormEvent,useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { apiRequest,API_URL } from "@/lib/api";
import { Loading,Notice,PageHead,SectionHead } from "@/components/ui";
type Asset={id:string;originalFilename:string;detectedMediaType:string;detectedContentType:string|null;sizeBytes:string;visibility:string;status:string;width:number|null;height:number|null;createdAt:string};
export default function Page(){const{assetId}=useParams<{assetId:string}>();const[a,setA]=useState<Asset|null>(null);const[m,setM]=useState("");const load=()=>apiRequest<{data:Asset}>(`/api/v1/media/${assetId}`).then(r=>setA(r.data)).catch(e=>setM(e.message));useEffect(()=>{load()},[assetId]);
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await apiRequest(`/api/v1/media/${assetId}`,{method:"PATCH",body:JSON.stringify({originalFilename:f.get("name"),visibility:f.get("visibility")})});setM("Media updated.");load()}async function process(){await apiRequest(`/api/v1/variants/media/${assetId}/process`,{method:"POST"});setM("Image variants generated.")}async function preview(){const r=await apiRequest<{data:{path:string}}>(`/api/v1/media/${assetId}/delivery-token`,{method:"POST",body:JSON.stringify({disposition:"inline"})});window.open(`${API_URL}${r.data.path}`,"_blank")}
return <><PageHead title="One asset, complete context." description="Metadata, delivery state and transformation controls stay together."><a className="mp-button" href="/dashboard/media">Back to media</a></PageHead><Notice message={m}/>{!a?<Loading/>:<><section><SectionHead title="Asset information" description={`Created ${new Date(a.createdAt).toLocaleString()} · ${a.status}`}/><form className="mp-form-grid" onSubmit={save}><div className="mp-field"><label htmlFor="name">Filename</label><input id="name" name="name" defaultValue={a.originalFilename}/></div><div className="mp-field"><label htmlFor="visibility">Visibility</label><select id="visibility" name="visibility" defaultValue={a.visibility}><option>PRIVATE</option><option>PUBLIC</option></select></div><div className="mp-field"><label>Content type</label><input value={a.detectedContentType??"Unknown"} disabled/></div><div className="mp-field"><label>Dimensions</label><input value={a.width&&a.height?`${a.width} × ${a.height}`:"Not available"} disabled/></div><div style={{display:"flex",gap:8}}><button className="mp-button" data-primary="true">Save changes</button><button type="button" className="mp-button" onClick={preview}>Open preview</button>{a.detectedMediaType==="IMAGE"&&<button type="button" className="mp-button" onClick={process}>Generate variants</button>}</div></form></section></>}</>}
