"use client";
import { FormEvent,useEffect,useState } from "react";
import { apiRequest,API_URL } from "@/lib/api";
import { Empty,Loading,Notice,PageHead } from "@/components/ui";
type Asset={id:string;originalFilename:string;detectedMediaType:string;detectedContentType:string|null;sizeBytes:string;visibility:"PRIVATE"|"PUBLIC";status:string;createdAt:string};
const bytes=(v:string)=>{let n=Number(v),i=0;const u=["B","KB","MB","GB","TB"];while(n>=1024&&i<4){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`};
export default function Page(){const[items,setItems]=useState<Asset[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[search,setSearch]=useState("");
async function load(){setLoading(true);try{const r=await apiRequest<{data:Asset[]}>(`/api/v1/media${search?`?search=${encodeURIComponent(search)}`:""}`);setItems(r.data)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function trash(id:string){await apiRequest(`/api/v1/media/${id}`,{method:"DELETE"});load()}async function visibility(a:Asset){await apiRequest(`/api/v1/media/${a.id}`,{method:"PATCH",body:JSON.stringify({visibility:a.visibility==="PUBLIC"?"PRIVATE":"PUBLIC"})});load()}async function download(a:Asset){const r=await apiRequest<{data:{path:string}}>(`/api/v1/media/${a.id}/delivery-token`,{method:"POST",body:JSON.stringify({disposition:"attachment"})});window.location.assign(`${API_URL}${r.data.path}`)}
function searchNow(e:FormEvent){e.preventDefault();load()}
return <><PageHead title="Every asset stays inspectable." description="Search, deliver, change visibility or move files through their complete lifecycle."><a className="mp-button" data-primary="true" href="/dashboard/upload">Upload</a></PageHead><Notice message={error} tone="error"/><form className="mp-form-grid" style={{gridTemplateColumns:"minmax(0,1fr) auto",marginBottom:28}} onSubmit={searchNow}><div className="mp-field"><label htmlFor="search">Filename</label><input id="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search media"/></div><button className="mp-button" style={{alignSelf:"end"}}>Search</button></form>{loading?<Loading/>:items.length===0?<Empty title="No matching media" text="Upload a file or change the current search."/>:<div className="mp-table-wrap"><table className="mp-table"><caption>{items.length} media assets</caption><thead><tr><th>Asset</th><th>Type</th><th className="mp-num">Size</th><th>Visibility</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><a className="mp-row-title" href={`/dashboard/media/${a.id}`}>{a.originalFilename}</a><div className="mp-row-meta">{a.detectedContentType??"Unknown type"}</div></td><td>{a.detectedMediaType}</td><td className="mp-num">{bytes(a.sizeBytes)}</td><td><button className="mp-button" onClick={()=>visibility(a)}>{a.visibility}</button></td><td>{a.status}</td><td>{new Date(a.createdAt).toLocaleDateString()}</td><td><div style={{display:"flex",gap:6}}><button className="mp-button" onClick={()=>download(a)}>Download</button><a className="mp-button" href={`/dashboard/media/${a.id}`}>Edit</a><button className="mp-button" data-danger="true" onClick={()=>trash(a.id)}>Trash</button></div></td></tr>)}</tbody></table></div>}</>}
