"use client";
import { FormEvent,useEffect,useState } from "react";
import { apiRequest } from "@/lib/api";
import { Loading,Notice,PageHead,SectionHead } from "@/components/ui";
type Key={id:string;name:string;prefix:string;scopes:string[];createdAt:string;lastUsedAt:string|null;revokedAt:string|null};
const scopes=["media:read","media:write","media:delete","folders:read","folders:write","uploads:write","usage:read"];
export default function Page(){const[keys,setKeys]=useState<Key[]>([]);const[secret,setSecret]=useState("");const[m,setM]=useState("");const[l,setL]=useState(true);const load=()=>apiRequest<{data:Key[]}>("/api/v1/api-keys").then(r=>setKeys(r.data)).catch(e=>setM(e.message)).finally(()=>setL(false));useEffect(()=>{load()},[]);
async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await apiRequest<{data:{rawKey:string}}>("/api/v1/api-keys",{method:"POST",body:JSON.stringify({name:f.get("name"),scopes:f.getAll("scopes")})});setSecret(r.data.rawKey);e.currentTarget.reset();load()}async function revoke(id:string){await apiRequest(`/api/v1/api-keys/${id}`,{method:"DELETE"});load()}
return <><PageHead title="Give machines only the access they need." description="Raw keys are displayed once. Stored secrets remain HMAC-hashed and every request is scope checked."/><Notice message={m} tone="error"/>{secret&&<div className="mp-notice" data-tone="warning"><strong>Copy this key now.</strong><div className="mp-mono" style={{marginTop:8,overflowWrap:"anywhere",userSelect:"all"}}>{secret}</div></div>}<div className="mp-form-grid"><section><SectionHead title="Create API key" description="Choose the smallest set of scopes required by the integration."/><form className="mp-form-grid" style={{gridTemplateColumns:"1fr"}} onSubmit={create}><div className="mp-field"><label htmlFor="key-name">Key name</label><input id="key-name" name="name" required/></div><fieldset style={{border:0,padding:0,margin:0}}><legend style={{fontSize:13,marginBottom:10}}>Scopes</legend><div className="mp-form-grid">{scopes.map(s=><label key={s} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" name="scopes" value={s}/><span className="mp-mono">{s}</span></label>)}</div></fieldset><button className="mp-button" data-primary="true">Create key</button></form></section><section><SectionHead title="Existing keys" description="Last-used data helps identify credentials that can be retired." />{l?<Loading/>:<div className="mp-list">{keys.map(k=><div className="mp-row" key={k.id}><div><div className="mp-row-title">{k.name}</div><div className="mp-row-meta mp-mono">{k.prefix}</div><div className="mp-row-meta">{k.scopes.join(", ")}</div></div>{k.revokedAt?<span>Revoked</span>:<button className="mp-button" data-danger="true" onClick={()=>revoke(k.id)}>Revoke</button>}</div>)}</div>}</section></div></>}
