"use client";
import { FormEvent,useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { Feedback,LoadingBlock } from "@/components/feedback";
import { apiRequest } from "@/lib/api";
type Folder={id:string;name:string;pathKey:string;mediaCount:number;children:Array<{id:string;name:string;pathKey:string}>};
export default function Page(){const {folderId}=useParams<{folderId:string}>();const [f,setF]=useState<Folder|null>(null);const [message,setMessage]=useState("");const load=()=>apiRequest<{data:Folder}>(`/api/v1/folders/${folderId}`).then(r=>setF(r.data)).catch(e=>setMessage(e.message));useEffect(()=>{load()},[folderId]);
 async function rename(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await apiRequest(`/api/v1/folders/${folderId}`,{method:"PATCH",body:JSON.stringify({name:d.get("name")})});setMessage("Folder updated.");load()}
 async function child(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await apiRequest("/api/v1/folders",{method:"POST",body:JSON.stringify({name:d.get("name"),parentId:folderId})});e.currentTarget.reset();load()}
 return <><PageHeader title="Folder details" subtitle="Rename and manage nested folders."><a className="btn btn-outline-secondary" href="/dashboard/folders">Back</a></PageHeader><Feedback message={message} variant="info"/>{!f?<LoadingBlock/>:<div className="row g-4"><div className="col-lg-5"><form className="card mb-4" onSubmit={rename}><div className="card-header"><strong>Folder settings</strong></div><div className="card-body"><label className="form-label">Name</label><input className="form-control" name="name" defaultValue={f.name}/><div className="form-text">{f.pathKey} · {f.mediaCount} media assets</div></div><div className="card-footer bg-white"><button className="btn btn-primary">Save</button></div></form><form className="card" onSubmit={child}><div className="card-header"><strong>Add child folder</strong></div><div className="card-body"><input className="form-control" name="name" placeholder="Child folder name" required/></div><div className="card-footer bg-white"><button className="btn btn-outline-primary">Create child</button></div></form></div><div className="col-lg-7"><div className="card"><div className="card-header"><strong>Child folders</strong></div><div className="list-group list-group-flush">{f.children.length?f.children.map(c=><a className="list-group-item list-group-item-action d-flex gap-3" href={`/dashboard/folders/${c.id}`} key={c.id}><i className="bi bi-folder-fill text-warning fs-4"/><div><strong>{c.name}</strong><div className="text-secondary small">{c.pathKey}</div></div></a>):<div className="p-4 text-secondary">No child folders.</div>}</div></div></div></div>}</>
}
