"use client";
import { FormEvent,useEffect,useState } from "react";
import { useParams } from "next/navigation";
import { apiRequest } from "@/lib/api";
import { Empty,Loading,Notice,PageHead,SectionHead } from "@/components/ui";
type Folder={id:string;name:string;pathKey:string;mediaCount:number;children:Array<{id:string;name:string;pathKey:string}>};
export default function Page(){const{folderId}=useParams<{folderId:string}>();const[f,setF]=useState<Folder|null>(null);const[m,setM]=useState("");const load=()=>apiRequest<{data:Folder}>(`/api/v1/folders/${folderId}`).then(r=>setF(r.data)).catch(e=>setM(e.message));useEffect(()=>{load()},[folderId]);
async function rename(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await apiRequest(`/api/v1/folders/${folderId}`,{method:"PATCH",body:JSON.stringify({name:d.get("name")})});setM("Folder updated.");load()}async function child(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await apiRequest("/api/v1/folders",{method:"POST",body:JSON.stringify({name:d.get("name"),parentId:folderId})});e.currentTarget.reset();load()}
return <><PageHead title="Folder hierarchy stays explicit." description="Rename the current folder or add children without losing its path."><a className="mp-button" href="/dashboard/folders">Back to folders</a></PageHead><Notice message={m}/>{!f?<Loading/>:<><section><SectionHead title={f.name} description={`${f.pathKey} · ${f.mediaCount} media assets`}/><form className="mp-form-grid" onSubmit={rename}><div className="mp-field"><label htmlFor="folder-name">Folder name</label><input id="folder-name" name="name" defaultValue={f.name}/></div><div style={{alignSelf:"end"}}><button className="mp-button" data-primary="true">Save</button></div></form></section><section className="mp-section"><SectionHead title="Child folders" description="Create another level only when the media structure needs it."/><form className="mp-form-grid" style={{gridTemplateColumns:"minmax(0,1fr) auto",marginBottom:28}} onSubmit={child}><div className="mp-field"><label htmlFor="child">Child folder name</label><input id="child" name="name" required/></div><button className="mp-button" style={{alignSelf:"end"}}>Create child</button></form>{f.children.length===0?<Empty title="No child folders" text="This folder currently ends the hierarchy."/>:<div className="mp-list">{f.children.map(c=><a className="mp-row" href={`/dashboard/folders/${c.id}`} key={c.id}><div><div className="mp-row-title">{c.name}</div><div className="mp-row-meta mp-mono">{c.pathKey}</div></div><span>Open</span></a>)}</div>}</section></>}</>}
